# Generated by Django 5.2.11 on 2026-03-09 07:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HederaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('token_type', models.CharField(choices=[('hbar', 'HBAR'), ('fungible', 'Fungible Token'), ('nft', 'Non-Fungible Token')], default='hbar', max_length=20)),
                ('token_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('consensus_timestamp', models.DateTimeField(blank=True, null=True)),
                ('from_account', models.CharField(max_length=50)),
                ('to_account', models.CharField(max_length=50)),
                ('memo', models.TextField(blank=True, null=True)),
                ('charged_fees', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=50)),
                ('token_name', models.CharField(blank=True, max_length=100, null=True)),
                ('token_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('token_type', models.CharField(choices=[('hbar', 'HBAR'), ('fungible', 'Fungible Token'), ('nft', 'Non-Fungible Token')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('serial_numbers', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code_expires',
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_account_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_account_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_creation', 'Pending Creation'), ('creation_failed', 'Creation Failed')], default='pending_creation', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_balance',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_balance_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_private_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hedera_recovery_phrase_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-24', '18-24 Years'), ('25-29', '25-29 Years'), ('30-35', '30-35 Years')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='account_aud_user_id_ac9442_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='account_otp_user_id_b04f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['code', 'expires_at'], name='account_otp_code_9ab1f5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='account_use_email_553b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hedera_account_id'], name='account_use_hedera__ca7fab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='account_use_phone_n_ed0b53_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='account_use_session_c064ec_idx'),
        ),
        migrations.AddField(
            model_name='hederatransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hedera_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hederatransaction',
            index=models.Index(fields=['user', '-created_at'], name='account_hed_user_id_869fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='hederatransaction',
            index=models.Index(fields=['transaction_id'], name='account_hed_transac_f770db_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenbalance',
            index=models.Index(fields=['user', 'token_type'], name='account_tok_user_id_31446b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenbalance',
            unique_together={('user', 'token_id')},
        ),
    ]
