# Generated by Django 5.2.11 on 2026-03-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_hederatransaction_tokenbalance_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='account_use_hedera__ca7fab_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hedera_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hedera_balance_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hedera_recovery_phrase_encrypted',
        ),
        migrations.AlterField(
            model_name='user',
            name='hedera_account_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending_creation', 'Pending Creation'), ('creation_failed', 'Creation Failed')], default='pending_creation', max_length=20, null=True),
        ),
    ]
