# Generated by Django 5.2.8 on 2026-02-12 13:40

import django.core.validators
import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_dividends', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loans_taken', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loans_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active_loans_count', models.IntegerField(default=0)),
                ('total_interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_deposit_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_withdrawal_used', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=finance.models.generate_uuid, max_length=50, unique=True)),
                ('purpose', models.CharField(choices=[('investment', 'Venture Investment'), ('personal', 'Personal'), ('business', 'Business'), ('emergency', 'Emergency'), ('education', 'Education')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('active', 'Active'), ('repaid', 'Fully Repaid'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tenure_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('repayment_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('lump_sum', 'Lump Sum')], default='monthly', max_length=20)),
                ('total_repayable', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('assessment_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('expected_repayment_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='core.investment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_account', 'Bank Account'), ('card', 'Card')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('expiry_month', models.CharField(blank=True, max_length=2)),
                ('expiry_year', models.CharField(blank=True, max_length=4)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('dividend', 'Dividend Payment'), ('loan', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('fee', 'Fee'), ('refund', 'Refund')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('wallet', 'Wallet Balance')], default='mpesa', max_length=20)),
                ('reference', models.CharField(default=finance.models.generate_uuid, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('mpesa_code', models.CharField(blank=True, max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=100)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dividend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.dividend')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.investment')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='finance.loan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayment', to='finance.transaction')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('locked_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('daily_deposit_limit', models.DecimalField(decimal_places=2, default=150000, max_digits=14)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=150000, max_digits=14)),
                ('remaining_daily_deposit', models.DecimalField(decimal_places=2, default=150000, max_digits=14)),
                ('remaining_daily_withdrawal', models.DecimalField(decimal_places=2, default=150000, max_digits=14)),
                ('last_deposit_at', models.DateTimeField(blank=True, null=True)),
                ('last_withdrawal_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'status'], name='finance_loa_user_id_d67224_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['reference'], name='finance_loa_referen_dfe2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='finance_tra_user_id_f69cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'initiated_at'], name='finance_tra_transac_4db00d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='finance_tra_referen_220685_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['mpesa_code'], name='finance_tra_mpesa_c_3807df_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='finance_tra_created_ef4f06_idx'),
        ),
    ]
