# Generated by Django 5.2.11 on 2026-03-10 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_mpesa_c_3807df_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='finance_tra_created_ef4f06_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='dividend',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='loan',
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_consensus_timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hedera_topic_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['hedera_message_id'], name='finance_tra_hedera__749c39_idx'),
        ),
    ]
