# Generated by Django 5.2.11 on 2026-03-10 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_transaction_finance_tra_mpesa_c_3807df_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
