# Generated by Django 5.2.11 on 2026-03-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0004_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dividend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.dividend'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.investment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.loan'),
        ),
    ]
