# Generated by Django 5.2.8 on 2024-02-26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='briefcase', help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Deal Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('reference', models.CharField(default=uuid.uuid4().hex[:12].upper, max_length=50, unique=True)),
                ('objective', models.TextField(help_text='Deal objective - what this deal aims to achieve')),
                ('description', models.TextField(help_text='Detailed description of the deal')),
                ('opt_in_amount', models.DecimalField(decimal_places=2, help_text='Fixed amount each member pays to opt in', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_capital_required', models.DecimalField(decimal_places=2, help_text='Total capital needed for the deal', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_opt_in_members', models.IntegerField(default=1, help_text='Minimum members needed for deal to proceed')),
                ('max_opt_in_members', models.IntegerField(blank=True, help_text='Maximum members allowed (null = unlimited)', null=True)),
                ('expected_operations', models.TextField(help_text='What the deal will do (not promised returns)')),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=20)),
                ('duration_months', models.IntegerField(help_text='Expected duration in months', validators=[django.core.validators.MinValueValidator(1)])),
                ('management_fee_percent', models.DecimalField(decimal_places=2, default=10.0, help_text='AML management fee percentage of net profit', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('performance_carry_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='AML performance carry percentage of profits', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('disclosed_at', models.DateTimeField(blank=True, null=True)),
                ('opt_in_start', models.DateTimeField(blank=True, null=True)),
                ('opt_in_end', models.DateTimeField(blank=True, null=True)),
                ('setup_start', models.DateTimeField(blank=True, null=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sourcing', 'Sourcing'), ('disclosed', 'Disclosed'), ('opt_in_open', 'Opt-In Open'), ('opt_in_closed', 'Opt-In Closed'), ('setup', 'Setup'), ('active', 'Active'), ('monitoring', 'Monitoring'), ('paused', 'Paused'), ('closed', 'Closed'), ('scaling', 'Scaling')], default='sourcing', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='deals/covers/')),
                ('total_opted_in', models.IntegerField(default=0)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='deals.dealcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='deals_deal_status_9b9f04_idx'), models.Index(fields=['reference'], name='deals_deal_referenc_8b7e8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DealCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('operating', 'Operating Cost'), ('staff', 'Staff Salary'), ('rent', 'Rent/Lease'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='deals.deal')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DealOptIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=uuid.uuid4().hex[:12].upper, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_ins', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_opt_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'deal')},
            },
        ),
        migrations.CreateModel(
            name='DealProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_costs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('management_fee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('performance_carry', models.DecimalField(decimal_places=2, max_digits=14)),
                ('members_share', models.DecimalField(decimal_places=2, max_digits=14)),
                ('distribution_per_member', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_members', models.IntegerField()),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='deals.deal')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DealReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period', models.DateField(help_text='Month/quarter of the report')),
                ('summary', models.TextField()),
                ('revenue_details', models.TextField(blank=True)),
                ('cost_details', models.TextField(blank=True)),
                ('aml_share', models.DecimalField(decimal_places=2, help_text='AML management fee + carry', max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status_update', models.CharField(help_text='e.g., Active, Monitoring, Closed', max_length=100)),
                ('next_steps', models.TextField(blank=True)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='deals/reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='deals.deal')),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='DealRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='deals.deal')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='DealUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]