# Generated by Django 5.2.8 on 2026-02-26 17:45

import deals.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial_categories'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_status_eccb1a_idx',
            old_name='deals_deal_status_9b9f04_idx',
        ),
        migrations.RenameIndex(
            model_name='deal',
            new_name='deals_deal_referen_e40443_idx',
            old_name='deals_deal_referenc_8b7e8a_idx',
        ),
        migrations.AddField(
            model_name='dealoptin',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='reference',
            field=models.CharField(default=deals.models.generate_uuid, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dealoptin',
            name='reference',
            field=models.CharField(default=deals.models.generate_uuid, max_length=50, unique=True),
        ),
    ]
