# Generated by Django 5.2.11 on 2026-03-12 14:17

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_rename_deals_deal_status_9b9f04_idx_deals_deal_status_eccb1a_idx_and_more'),
        ('finance', '0005_transaction_dividend_transaction_investment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='expected_end_date',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='setup_start',
        ),
        migrations.AddField(
            model_name='deal',
            name='hedera_metadata_uri',
            field=models.URLField(blank=True, help_text='URI to collection metadata on IPFS', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='hedera_supply_key_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted supply key for minting NFTs', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='hedera_token_id',
            field=models.CharField(blank=True, help_text='Hedera Token ID for this NFT collection', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='hedera_topic_id',
            field=models.CharField(blank=True, help_text='Hedera topic for deal updates', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealoptin',
            name='hedera_message_id',
            field=models.CharField(blank=True, help_text='Hedera message ID for NFT minting', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealoptin',
            name='hedera_nft_id',
            field=models.CharField(blank=True, help_text='Full NFT ID (token_id/serial)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealoptin',
            name='hedera_serial_number',
            field=models.IntegerField(blank=True, help_text='NFT serial number for this opt-in', null=True),
        ),
        migrations.AddField(
            model_name='dealprofitdistribution',
            name='distribution_topic_id',
            field=models.CharField(blank=True, help_text='Hedera topic for distribution record', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dealreport',
            name='hedera_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dealupdate',
            name='hedera_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='duration_months',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='expected_operations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='management_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='max_opt_in_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='min_opt_in_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='deal',
            name='objective',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='opt_in_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='performance_carry_percent',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deal',
            name='total_capital_required',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='dealcategory',
            name='icon',
            field=models.CharField(default='briefcase', max_length=50),
        ),
        migrations.AlterField(
            model_name='dealreport',
            name='aml_share',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dealreport',
            name='period',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dealreport',
            name='status_update',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['hedera_token_id'], name='deals_deal_hedera__711acb_idx'),
        ),
        migrations.AddIndex(
            model_name='dealoptin',
            index=models.Index(fields=['user', 'status'], name='deals_dealo_user_id_0d666b_idx'),
        ),
        migrations.AddIndex(
            model_name='dealoptin',
            index=models.Index(fields=['hedera_nft_id'], name='deals_dealo_hedera__a053d9_idx'),
        ),
    ]
