# Generated by Django 5.2.11 on 2026-03-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_remove_deal_expected_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealoptin',
            name='nft_image',
            field=models.ImageField(blank=True, help_text='Generated NFT image proof', null=True, upload_to='nft_proofs/'),
        ),
    ]
